### ISSUE TITLE
Create a setup.py for the game

### ISSUE THREAD

**Issue by douglascdev** [douglas-cpp/snake#24]
Create a setup.py for the game, making it possible to install the package with pip.

**Comment by AdityaJ7** [comment]
Hello @douglas-cpp I would like to work on this issue

**Comment by douglascdev** [comment]
@AdityaJ7 sure, go ahead, I'll assign it to you

**Comment by douglascdev** [comment]
@AdityaJ7 before I close the Issue, did the pre-commit hook work out for you? I saw that your first two commits were not formatted, so let me know it it's the hook's fault so I can fix it.
 And thank you again for contributing, feel free to take any issue or make your own changes :)

**Comment by AdityaJ7** [comment]
> @AdityaJ7 before I close the Issue, did the pre-commit hook work out for you? I saw that your first two commits were not formatted, so let me know it it's the hook's fault so I can fix it.
> And thank you again for contributing, feel free to take any issue or make your own changes :)

It works fine for me . It failed earlier due to the presence of `''` instead of `""`.
Here is a screenshot for the pre-commit that I checked on the files
![Capture](https://user-images.githubusercontent.com/42397096/92551759-76219400-f27c-11ea-9a45-c0a3b6353a0c.PNG)
