### ISSUE TITLE
Display player's score

### ISSUE THREAD

**Issue by douglascdev** [douglas-cpp/snake#7]
- Make an integer attribute in the Snake class to hold the score
- Increment it when food collision is detected(detection already exists)
- Create a text object that displays the player's score on screen

**Comment by GhostUser** [comment]
Can I take this?

**Comment by douglascdev** [comment]
Sure, go ahead!

**Comment by douglascdev** [comment]
I said you should create a new attribute, but you can actually just use the length of the snake as score, since a new unit is added for each food it eats. It could be less efficient though, so it's up to you.

**Comment by GhostUser** [comment]
instead of creating a attribute I just added the score feature, but I'll  try to put the code in a attribute tomorrow. As rn I think I made the code little ugly.

**Comment by GhostUser** [comment]
Added the update function. Was working with old main.py. lol

**Comment by douglascdev** [comment]
Done, thank you for another contribution
